### ISSUE TITLE
GPU vs CPU

### ISSUE THREAD

**Issue by morawi** [subhadarship/kmeans_pytorch#10]
I did not see any significant difference in GPU vs CPU speed. I noticed that only the data size has highly been changed, and number of clusters were a bit low 2, 3 ...  speaking of this [test](https://github.com/subhadarship/kmeans_pytorch/blob/master/cpu_vs_gpu.ipynb).
I hope I am not wrong, I think what really matters here with regard to speed is the number of clusters. Hence, re running the experiment with higher number of clusters would show the speed significance, if any. I would go up to 64 clusters.

**Comment by subhadarship** [comment]
actually the [notebook](https://github.com/subhadarship/kmeans_pytorch/blob/master/cpu_vs_gpu.ipynb) just illustrates the idea of comparison between GPU and CPU performances for `num_clusters = 3`. Using bigger `num_clusters` will likely result in increasing the gap between GPU and CPU perfs.

**Comment by morawi** [comment]
agreed. That was my point. I expect to see speed significance if the number of clusters go higher.

**Comment by subhadarship** [comment]
yup

**Comment by zaemyung** [comment]
There is a bug in the current code that the distance metrics will always be calculated using cpu regardless of the device setting:
https://github.com/subhadarship/kmeans_pytorch/blob/e32bf4d67b55f673473790c309e978e752a84e8e/kmeans_pytorch/__init__.py#L127-L162

This is because the `pairwise_distance_function` is called without the `device` argument, and it will be replaced with the default device which is cpu.
I made a quick fix in my pull request by passing the device argument through `functools.partial`:
```python
if distance == 'euclidean':
        pairwise_distance_function = partial(pairwise_distance, device=device)
    elif distance == 'cosine':
        pairwise_distance_function = partial(pairwise_cosine, device=device)
    elif distance == 'soft_dtw':
        sdtw = SoftDTW(use_cuda=device.type == 'cuda', gamma=gamma_for_soft_dtw)
        pairwise_distance_function = partial(pairwise_soft_dtw, sdtw=sdtw, device=device)
    else:
        raise NotImplementedError
```

**Comment by morawi** [comment]
> There is a bug in the current code that the distance metrics will always be calculated using cpu regardless of the device setting:
> https://github.com/subhadarship/kmeans_pytorch/blob/e32bf4d67b55f673473790c309e978e752a84e8e/kmeans_pytorch/__init__.py#L127-L162
> 
> This is because the `pairwise_distance_function` is called without the `device` argument, and it will be replaced with the default device which is cpu.
> I made a quick fix in my pull request (#19) by passing the device argument through `functools.partial`:
> 
> ```python
> if distance == 'euclidean':
>         pairwise_distance_function = partial(pairwise_distance, device=device)
>     elif distance == 'cosine':
>         pairwise_distance_function = partial(pairwise_cosine, device=device)
>     elif distance == 'soft_dtw':
>         sdtw = SoftDTW(use_cuda=device.type == 'cuda', gamma=gamma_for_soft_dtw)
>         pairwise_distance_function = partial(pairwise_soft_dtw, sdtw=sdtw, device=device)
>     else:
>         raise NotImplementedError
> ```

I considered your suggestion. Yet, I took the the comparison to a different level by comparing to `sklearn KMeans` (which solely runs on CPU).  I am clustering with `num_clusters=10`  on 3D data of length 66871,  

```
X.shape
(66871, 3)

```
```
sklearnKmeans-time is ~ 10 seconds (almost always)
kmeans_pytorch-time is ~ sometimes 0.7 seconds, 18 seconds, and can get to 60 seconds.
```

That being said aside from any quantitative convergence performance. Maybe it worth highlighting the parameters I used to build the `sklearn KMeans` model:

```
model = KMeans(n_clusters = K, 
                 n_init=8, 
                 random_state=np.random.randint(0, 1e6),
                 tol=1e-6, 
                 max_iter=500, 
                 init='k-means++')
model.fit(X)
labels = model.predicet(X)

```

Clearly, the problem with `kmeans_pytorch` is the need to control the `max_iter`, and probably, adding `n_init` (number of initializations), using k-means++ (mimicking sklearn KMeans).

**Comment by zaemyung** [comment]
@morawi 
I think the `max_iter` can be set by `iter_limit`:
https://github.com/subhadarship/kmeans_pytorch/blob/7eddae7f6b74cbb60a6028e6693225501c61a15e/kmeans_pytorch/__init__.py#L30

As for the addition of `n_init` and `init` methods, I think it you can create a separate issue for them (and contribute ! :D )

**Comment by zaemyung** [comment]
@morawi 
Actually, you might also consider: https://docs.rapids.ai/api/cuml/stable/api.html?highlight=kmeans#cuml.dask.cluster.KMeans

**Comment by morawi** [comment]
> iter_limit=0,

Did not notice in the midst of the rush. 

Yet, digging into the code seems that default `iter_limit=0` will let the run go into an infinite loop:
`[if iter_limit != 0 and iteration >= iter_limit](https://github.com/subhadarship/kmeans_pytorch/blob/7eddae7f6b74cbb60a6028e6693225501c61a15e/kmeans_pytorch/__init__.py#L116)`

Am I missing something here?

**Comment by zaemyung** [comment]
Yes, the default it 0. You need to set the value other than 0 if you wish it to take effect.
