### ISSUE TITLE
Quick and dirty fix for "Can't choose a cluster if two points are too close to each other, that's where the nan come"

### ISSUE THREAD

**Issue by DeepOzean** [subhadarship/kmeans_pytorch#16]
Hey, thanks for the pytorch kmeans implementation. I also encountered the following problem and have a solution for it:
Add the following line into line 84 in kmeans_pytorch/__init__.py
```
            if selected.shape[0] == 0:
                selected = X[torch.randint(len(X), (1,))]
```

The problem is, if two centroids are too close together, then one centroid gets all the close points, leaving the other centroid with zero assigned points. If that happens, that centroid's selected points is an empty list. The above code detects that and then chooses a new point to replace that centroid randomly. I guess there are more elegant solution in choosing the replacement point. But this works and converges. So a quick and dirty fix.

Sorry I write it here, it should be a pull request, but I am new to GitHub.

**Comment by zaemyung** [comment]
@DeepOzean 's fix added to https://github.com/subhadarship/kmeans_pytorch/pull/19
