### ISSUE TITLE
tqdm_flag missing

### ISSUE THREAD

**Issue by morawi** [subhadarship/kmeans_pytorch#23]
I had to change the code to remove verbosity.
Why `tqdm_flag` is missing?

**Comment by AnthoOzier** [comment]
According to #14 you may have the code from pip and not from github. Actually I am also trying to remove the verbosity and I am not successful yet, did you find a solution ?

**Comment by morawi** [comment]
> did you find a solution ?

I manually removed all std.out.

**Comment by subhadarship** [comment]
#24
