### ISSUE TITLE
Initialize with setting Seed

### ISSUE THREAD

**Issue by sprenkamp** [subhadarship/kmeans_pytorch#30]
Hi, as far as I understand it is not possible to set a seed to reproduce the results of the algorithm. I am I correct here?
I looked at the code and it would be quite simple to edit I believe, are you interested in adding the function and can I participate?

**Comment by subhadarship** [comment]
Yes the current implementation doesn't set a random seed. Totally feel free to contribute and create a pull request

**Comment by sprenkamp** [comment]
Hi subhadarship, can you give me Permission to push to the repo? I have a first draft that works, at which you can look at.

**Comment by subhadarship** [comment]
Create a pull request
