### ISSUE TITLE
kmeans_predict super slow with print

### ISSUE THREAD

**Issue by csmaster23** [subhadarship/kmeans_pytorch#4]
On line 103 of file __init__.py for the method kmeans_predict, can you make the print an option for a verbose mode (or just delete it). If it gets called a lot the print really slows everything down

**Comment by subhadarship** [comment]
Thanks for mentioning that! I will add a verbose option. Look out for this change in the next release !!

**Comment by csmaster23** [comment]
Thanks! Great code btw!

**Comment by subhadarship** [comment]
Thanks for the appreciation

**Comment by AmingWu** [comment]
Dear Authors,
How can I quit the print?
